# -*- coding: utf-8 -*-
"""Civ pools for randomised team balancing, plus "which civs has this channel played
today".

WHAT CHANGED IN STAGE 5c: the per-civ win-rates this module ranks on come from the
derived-community `civ_stats` table, which nammaoe2bot/derived/civ_stats.py aggregates from
`civ_picks` once per refresh pass. Two sources were deleted to get there:

  * data/civ_elo_stats.csv, loaded into a module-global dict at import and used as a
    fallback whenever the live numbers were thin. It was the bot's last runtime CSV
    read (identity v2 retired the others), it was a frozen snapshot from April that
    nothing regenerated, and "fall back to last quarter's numbers" is not a smaller
    version of "use this community's numbers" — it is a different, unlabelled claim.
    bot/web.py's /api/civ-stats endpoint was the file's last reader; stage 5d repointed
    it at the same derived-community table and deleted the CSV outright. Nothing in the
    repo reads it and the file is gone from disk (tests/test_web_repoint.py pins both).
    data/player_civ_stats.csv is a DIFFERENT file, still tracked, still regenerated by
    utils/civ_analysis.py, and unrelated to this paragraph.
  * the live `SELECT ... FROM civ_picks GROUP BY civ` this module used to run, which
    was the same aggregation civ_stats now stores, computed per call and across every
    channel in the database regardless of community.

Reading the table instead makes the numbers per COMMUNITY, which is the whole point of
the derived-community layer: two communities sharing a player must be able to disagree
about their civ meta.

NO IMPORTER TODAY, stated so the next reader does not go looking for one: the civ-pool
posts that called pick_balanced_teams were dropped in 6f33bc4, and get_today_civs lost
its caller with /test_random_civs. The module is kept (not deleted) because the feature
is expected back and this is the correct shape for it; it is exercised by
tests/test_civ_stats.py alone until then.

NAME COLLISION, DELIBERATE: nammaoe2bot/derived/civ_stats.py is a completely different module
— it WRITES the table this one reads. Neither imports the other.
"""
import random
from datetime import datetime, timezone, timedelta

from nammaoe2bot.runtime.database import db

# A civ needs this many games in the community before it is used for balanced pools.
# Applied here, at read time, rather than in the stored table: civ_stats is a plain
# tally with no opinion about what counts as enough evidence, and a second reader with
# a different threshold must not need a schema change.
MIN_CIV_GAMES = 50

IST = timezone(timedelta(hours=5, minutes=30))


async def civ_winrates(community_id):
    """{civ: {"civ", "games", "winrate"}} for one community, over civs with at least
    MIN_CIV_GAMES games. Empty when the community has no civ_stats rows yet — the
    caller must treat that as "no pools", never as "every civ is 50%".

    `games` is the row's own games count, and games == wins + losses holds by
    construction on every stored row (see nammaoe2bot/derived/civ_stats.py's
    compute_civ_stats): an unresolved outcome is counted into none of the three, so
    this division never quietly averages in a game nobody won.
    """
    rows = await db.fetchall(
        "SELECT civ, games, wins FROM civ_stats WHERE community_id=%s AND games >= %s",
        [community_id, MIN_CIV_GAMES])
    out = {}
    for r in rows or []:
        games = int(r["games"] or 0)
        if not games or not r["civ"]:
            continue
        out[r["civ"]] = {"civ": r["civ"], "games": games, "winrate": int(r["wins"] or 0) / games}
    return out


def pick_balanced_teams(civ_data, excluded_civs=None):
    """Pick 5 civs for each team, balanced by winrate with variety.

    `civ_data` is {civ: {"civ", "games", "winrate"}} — civ_winrates' output. It is a
    required argument rather than a default-to-the-module-seed: there is no seed any
    more, and a pure function that silently picks its own data source is exactly how
    the CSV fallback stayed live for a year after the DB copy existed. Returns
    (team_a, team_b), or None when there is no data.
    """
    all_civs = civ_data
    if not all_civs:
        return None

    # Remove excluded civs (case-insensitive match)
    excluded_lower = {c.lower() for c in (excluded_civs or [])}
    available = [c for c in all_civs.values() if c["civ"].lower() not in excluded_lower]

    # If not enough unique civs, allow repeats from the excluded set
    if len(available) < 10:
        available = list(all_civs.values())

    # Sort by winrate to create tiers
    by_wr = sorted(available, key=lambda c: c["winrate"], reverse=True)
    third = len(by_wr) // 3

    top_tier = by_wr[:third]
    mid_tier = by_wr[third:2 * third]
    bot_tier = by_wr[2 * third:]

    # Pick from each tier: 4 top, 2 mid, 4 bottom = 10 total
    def sample(pool, n):
        return random.sample(pool, min(n, len(pool)))

    top_picks = sample(top_tier, 4)
    mid_picks = sample(mid_tier, 2)
    bot_picks = sample(bot_tier, 4)

    all_picks = top_picks + mid_picks + bot_picks

    # If we got fewer than 10 (small pool), pad from remaining available
    if len(all_picks) < 10:
        used = {c["civ"] for c in all_picks}
        remaining = [c for c in available if c["civ"] not in used]
        all_picks += sample(remaining, 10 - len(all_picks))

    # Sort all 10 by winrate descending for snake draft
    all_picks.sort(key=lambda c: c["winrate"], reverse=True)

    # Snake draft: A, B, B, A, A, B, B, A, A, B
    team_a, team_b = [], []
    pattern = [0, 1, 1, 0, 0, 1, 1, 0, 0, 1]  # 0=A, 1=B
    for i, civ in enumerate(all_picks[:10]):
        if pattern[i] == 0:
            team_a.append(civ)
        else:
            team_b.append(civ)

    # Sort each team by winrate desc for display
    team_a.sort(key=lambda c: c["winrate"], reverse=True)
    team_b.sort(key=lambda c: c["winrate"], reverse=True)

    return team_a, team_b


async def get_today_civs(channel):
    """Civs already played in this channel today (IST).

    Reads `civ_picks` directly and deliberately NOT the civ_stats table above: this is
    a question about one channel in the last few hours, and civ_stats is a per-community
    lifetime tally with no time dimension and no channel dimension. Returns a set of
    civ name strings.
    """
    today_start = int(
        datetime.now(IST).replace(hour=0, minute=0, second=0, microsecond=0).timestamp()
    )
    rows = await db.fetchall(
        "SELECT DISTINCT civ FROM civ_picks WHERE channel_id=%s AND at >= %s",
        [channel.id, today_start]
    )
    return {r["civ"] for r in rows if r["civ"]}
