# -*- coding: utf-8 -*-
"""Loader/merger for the alternate-rating snapshot behind /leaderboard_alternate.

The snapshot (data/alt_ratings.csv) is a what-if: each player's Elo as it would
be if the blanket weekly uncertainty (sigma) decay had only ever applied to
inactive players, replayed from the start of that regime. It is regenerated by
utils/compute_alt_ratings.py. This module only reads the CSV and merges it with
the live leaderboard — kept dependency-free (stdlib) so it is unit-testable and
cheap to call.
"""
from __future__ import annotations

import csv
from pathlib import Path

_ALT_PATH = Path(__file__).resolve().parent.parent / "data" / "alt_ratings.csv"


def load_alt_ratings(path=_ALT_PATH):
	"""Return ``{user_id: {'alt_rating': int, 'alt_deviation': int}}`` from the snapshot.

	Missing file or unparseable rows are skipped rather than raising, so the
	command degrades gracefully to "no snapshot" instead of erroring.
	"""
	out = {}
	try:
		with open(path, newline="", encoding="utf-8") as f:
			for row in csv.DictReader(f):
				try:
					out[int(row["user_id"])] = {
						"alt_rating": int(row["alt_rating"]),
						"alt_deviation": int(row["alt_deviation"]),
					}
				except (ValueError, KeyError, TypeError):
					continue
	except FileNotFoundError:
		return {}
	return out


def load_snapshot_meta(path=_ALT_PATH):
	"""Return ``{'branch_date': str, 'computed_date': str}`` from the first row, or {}."""
	try:
		with open(path, newline="", encoding="utf-8") as f:
			for row in csv.DictReader(f):
				return {
					"branch_date": row.get("branch_date", ""),
					"computed_date": row.get("computed_date", ""),
				}
	except FileNotFoundError:
		return {}
	return {}


def build_alt_leaderboard(players, alt_map):
	"""Merge live players with the snapshot, sorted by alternate Elo (desc).

	``players`` is the live leaderboard (dicts with user_id/nick/rating). A player
	absent from the snapshot falls back to their current rating (delta 0), so newly
	joined players still appear.
	"""
	rows = []
	for p in players:
		alt = alt_map.get(p["user_id"])
		alt_rating = alt["alt_rating"] if alt else p["rating"]
		rows.append({
			"user_id": p["user_id"],
			"nick": p["nick"],
			"current": p["rating"],
			"alt": alt_rating,
			"delta": alt_rating - p["rating"],
		})
	rows.sort(key=lambda r: r["alt"], reverse=True)
	return rows
